### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by xiongchiamiov** [iFixit/itbrokeand.ifixit.com#16]
I'm not sure how we missed this, considering I've made it a personal campaign to get every project on Github having an explicit license, but somehow we don't have one.  I'm thinking CC-BY or CC-BY-NC?

We need to make sure to ask @treyhunner, too, since I've already merged in his commit.

**Comment by danielbeardsley** [comment]
I vote for CC-BY. I don't care what anyone does with our blog content.

**Comment by treyhunner** [comment]
@xiongchiamiov consider my extremely minor change to be under whatever open license you're using.  Creative Commons (or even anything on http://opensource.org/) seems appropriate.
