### ISSUE TITLE
Write about php-call-site-stats

### ISSUE THREAD

**Issue by xiongchiamiov** [iFixit/itbrokeand.ifixit.com#25]
[It](https://github.com/danielbeardsley/php-call-site-stats) is a cool little project, so we should tell people about it. :)

**Comment by danielbeardsley** [comment]
Good call. Maybe I'll do that.

**Comment by danielbeardsley** [comment]
Working on it: https://github.com/iFixit/itbrokeand.ifixit.com/compare/gh-pages...post--php-call-site-stats

**Comment by danielbeardsley** [comment]
Done : http://itbrokeand.ifixit.com/2014/04/01/introducing-php-call-site-stats.html
